### ISSUE TITLE
Fix API NewWriter api to receive io.Writer and not a filename

### ISSUE THREAD

**Issue by dakerfp** [kshedden/gonpy#1]
Making this, conforms the API as the other examples in the standard library.

**Comment by kshedden** [comment]
Thanks for the comment.  I agree the naming is unconventional but changing it would involve a compatibility break (the requested functionality is already present under names `ReaderFromStream` and `WriterFromStream`).  

At this point, I added more conventional alternative names `NewFileWriter` and `NewFileReader` and marked `NewReader` and `NewWriter` for possible incompatible changes in the future.

**Comment by kshedden** [comment]
I updated the API so that the names are more conventional, as suggested above.
