### ISSUE TITLE
load slow when a large slice and a solve method

### ISSUE THREAD

**Issue by xiaotianlis** [kshedden/gonpy#4]
When the array in npy file is large, the function such as GetFloat32 is very slow.
examle: array size in npy is  4 * 10000 * 10000, then I call function GetFloat32, consumer about 5mins.

Then I check the function GetFloat32, it like blow:
	data := make([]float32, rdr.n_elt)
	for k := 0; k < rdr.n_elt; k++ {
		err := binary.Read(rdr.r, rdr.Endian, &data[k])
		if err != nil {
			return nil, err
		}
	}

check the binary.Read function, found the function support read to slice instead of one value, and I change the code to:
	data := make([]float32, rdr.n_elt)
	err := binary.Read(rdr.r, rdr.Endian, data)
	if err != nil {
		return nil, err
	}

after change the code, I check the item in slice data is same as parse one by one, and GetFloat32 function now only take 15 seconds. so my question is there any reason that do not use binary.Read to slice?

Thank You.

**Comment by xiaotianlis** [comment]
I change all the GetX Function and run go test, it passed.

**Comment by kshedden** [comment]
@xiaotianlis, thanks for pointing this out.  I have incorporated your changes.  FYI in the process of doing this I ended up templatizing everything.
