### ISSUE TITLE
Unable to use gonpy.WriterFromStream

### ISSUE THREAD

**Issue by dtracers** [kshedden/gonpy#7]
WriterFromStream is not available to me when I try to compile and run this

```
f, _ := os.Create(fileName + ".npy.gz")
defer helpers.Close(f)
g := gzip.NewWriter(f)
w, _ := gonpy.WriterFromStream(g)
w.Shape = []int{}
```

![image](https://user-images.githubusercontent.com/1933836/118887671-854aee00-b8af-11eb-9291-16cc9cb79d91.png)

**Comment by dtracers** [comment]
Ah never mind the Readme is wrong and out of date.

It should be
```
gonpy.NewWriter
```

**Comment by kshedden** [comment]
Thanks, I have updated the README.
